default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER", "postgresql") %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

development:
  <<: *default
  database: dronehub_development

test:
  <<: *default
  database: dronehub_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "dronehub_production") %>
  url: <%= ENV["DATABASE_URL"] %>
