"use client";

import { useEffect, useState } from "react";
import { Building2, CheckCircle2, LockKeyhole, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { operatorApi, type OperatorPayoutProfile } from "@/lib/api/operator";
import type { ApiError } from "@/lib/api/client";

const EMPTY: OperatorPayoutProfile = { configured: false, account_kind: "business", billing: {}, verification_status: "unverified" };

export default function OperatorBankInformationPage() {
  const [profile, setProfile] = useState<OperatorPayoutProfile>(EMPTY);
  const [form, setForm] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { operatorApi.payoutProfile().then(({ data }) => { setProfile(data); setForm({ account_kind: data.account_kind, legal_name: data.billing.legal_name || "", billing_email: data.billing.billing_email || "", tax_id: data.billing.tax_id || "", account_holder_name: data.account_holder_name || "", bank_name: data.bank_name || "", swift_bic: data.swift_bic || "", paypal_email: data.paypal_email || "" }); }).catch((reason: ApiError) => setError(reason.detail || reason.title || "Não foi possível carregar os dados bancários.")).finally(() => setLoading(false)); }, []);
  const set = (name: string, value: string) => setForm((current) => ({ ...current, [name]: value }));
  const field = (name: string, label: string, type = "text") => <label className="block text-sm font-medium text-slate-700">{label}<Input className="mt-1.5 h-11 border-slate-200" type={type} value={form[name] || ""} onChange={(event) => set(name, event.target.value)} /></label>;
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(null); try { const response = await operatorApi.updatePayoutProfile({ account_kind: form.account_kind, billing: { legal_name: form.legal_name, billing_email: form.billing_email, tax_id: form.tax_id }, bank_account: { account_holder_name: form.account_holder_name, account_number: form.account_number, bank_name: form.bank_name, swift_bic: form.swift_bic }, paypal_email: form.paypal_email }); setProfile(response.data); setForm((current) => ({ ...current, account_number: "" })); setNotice("Dados salvos. Informações bancárias são armazenadas somente de forma mascarada."); } catch (reason) { const apiError = reason as ApiError; setError(apiError.detail || apiError.title || "Não foi possível salvar."); } finally { setSaving(false); } }
  if (loading) return <div className="mx-auto max-w-4xl animate-pulse rounded-3xl bg-slate-100 p-20" />;
  return <div className="mx-auto max-w-4xl pb-12"><div className="flex items-start gap-4 border-b border-slate-200 pb-6"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-100 text-violet-700"><Building2 className="h-6 w-6" /></span><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-violet-600">Payouts</p><h1 className="mt-1 text-3xl font-bold text-slate-950">Bank information</h1><p className="mt-2 text-sm leading-6 text-slate-600">Configure os dados para recebimento após a conclusão dos pedidos.</p></div></div><div className="mt-6 flex items-center gap-3 rounded-xl border border-violet-100 bg-violet-50 p-4 text-sm text-violet-900"><LockKeyhole className="h-5 w-5 shrink-0" />A DroneHub não armazena o número integral da sua conta. Para integração de pagamentos, use um token do provedor.</div>{profile.configured && <div className="mt-5 flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800"><CheckCircle2 className="h-4 w-4" />Conta configurada{profile.bank_account_last4 ? ` •••• ${profile.bank_account_last4}` : ""} — verificação: {profile.verification_status}.</div>}<form onSubmit={save} className="mt-7 space-y-7 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><section><h2 className="text-lg font-bold text-slate-950">Dados de faturamento</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><label className="block text-sm font-medium text-slate-700">Tipo de conta<select className="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-white px-3" value={form.account_kind || "business"} onChange={(event) => set("account_kind", event.target.value)}><option value="business">Empresa</option><option value="personal">Pessoa física</option></select></label>{field("legal_name", "Nome legal / razão social")}{field("billing_email", "E-mail financeiro", "email")}{field("tax_id", "Documento fiscal")}</div></section><section className="border-t border-slate-100 pt-7"><h2 className="text-lg font-bold text-slate-950">Conta bancária</h2><p className="mt-1 text-sm text-slate-500">Ao salvar, o número será imediatamente descartado e apenas os últimos quatro dígitos serão exibidos.</p><div className="mt-5 grid gap-5 md:grid-cols-2">{field("account_holder_name", "Titular da conta")}{field("bank_name", "Banco")}{field("account_number", "Número da conta", "password")}{field("swift_bic", "SWIFT / BIC")}{field("paypal_email", "PayPal (opcional)", "email")}</div></section>{notice && <p className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</p>}{error && <p className="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}<div className="flex justify-end border-t border-slate-100 pt-6"><Button disabled={saving} type="submit"><Save className="h-4 w-4" />{saving ? "Salvando…" : "Salvar dados"}</Button></div></form></div>;
}
