"use client";

import { useState } from "react";
import { LifeBuoy, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { operatorApi } from "@/lib/api/operator";
import type { ApiError } from "@/lib/api/client";

export default function OperatorSupportPage() {
  const [form, setForm] = useState({ subject: "", category: "general", priority: "normal", message: "" });
  const [sending, setSending] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const set = (name: keyof typeof form, value: string) => setForm((current) => ({ ...current, [name]: value }));
  async function send(event: React.FormEvent) { event.preventDefault(); setSending(true); setError(null); try { const result = await operatorApi.createSupportRequest(form); setNotice(`Solicitação ${result.data.id.slice(0, 8)} criada. Nossa equipe entrará em contato.`); setForm({ subject: "", category: "general", priority: "normal", message: "" }); } catch (reason) { const apiError = reason as ApiError; setError(apiError.detail || apiError.title || "Não foi possível enviar a solicitação."); } finally { setSending(false); } }
  return <div className="mx-auto max-w-4xl pb-12"><div className="text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-violet-100 text-violet-700"><LifeBuoy className="h-7 w-7" /></span><p className="mt-5 text-xs font-bold uppercase tracking-[0.18em] text-violet-600">Support</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Como podemos ajudar?</h1><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-600">Envie uma solicitação para dúvidas de perfil, convites, pagamentos ou questões técnicas.</p></div><form onSubmit={send} className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="grid gap-5 md:grid-cols-2"><label className="md:col-span-2 block text-sm font-medium text-slate-700">Assunto<Input required className="mt-1.5 h-11 border-slate-200" value={form.subject} onChange={(event) => set("subject", event.target.value)} /></label><label className="block text-sm font-medium text-slate-700">Categoria<select className="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-white px-3" value={form.category} onChange={(event) => set("category", event.target.value)}><option value="general">Geral</option><option value="onboarding">Cadastro</option><option value="payments">Pagamentos</option><option value="mission">Missões</option><option value="technical">Técnico</option></select></label><label className="block text-sm font-medium text-slate-700">Prioridade<select className="mt-1.5 h-11 w-full rounded-lg border border-slate-200 bg-white px-3" value={form.priority} onChange={(event) => set("priority", event.target.value)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label className="md:col-span-2 block text-sm font-medium text-slate-700">Mensagem<Textarea required className="mt-1.5 min-h-40 border-slate-200" value={form.message} onChange={(event) => set("message", event.target.value)} placeholder="Descreva o contexto e inclua links ou identificadores da missão quando possível." /></label></div>{notice && <p className="mt-6 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</p>}{error && <p className="mt-6 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-800">{error}</p>}<div className="mt-6 flex justify-end"><Button disabled={sending} type="submit"><Send className="h-4 w-4" />{sending ? "Enviando…" : "Enviar solicitação"}</Button></div></form></div>;
}
